Fix/numeric provider state param
SEEK-Jobs/pact-net pull request #506
Opened 2024-06-10 12:02 UTC by YOU54F

fixes #449 

- Added examples of generating provider states with number or string values
- Serialise value into json, prior to sending over the wire
  - As per recommendation in https://github.com/pact-foundation/pact-reference/issues/263#issuecomment-1510555100
  - As per pact-js https://github.com/pact-foundation/pact-js/blob/54087fa06e485f1c7041a0a6f7f14e1cc177e09f/src/v3/pact.ts#L100-L102

relates to

- https://github.com/pact-foundation/pact-reference/issues/298
- https://github.com/pact-foundation/pact-reference/issues/263

2024-06-16 16:11 UTC, adamrodger requested changes
If the API is to open up to allow absolutely anything be used as a provider state parameter and change the public API then I'd want to see more significant testing of "weird" values.

So there are obvious things like what does `double.NaN` do? What about null or other nullable value types? What about complex objects? What about random classes being passed in? What about string-like types such as `StringBuilder` and `Span<char>`? What about arrays or other collection types? Stuff like that.

We also need a lot of round trip testing, to make sure that the provider tests can actually deserialise these things. I know we expect users to handle provider states themselves but we at least need to make sure that `System.Text.Json` can round trip these things given that's the main serialiser we support.

Using `object` in a public API creates a lot of opportunity for that to all go wrong so I think we need much more comprehensive testing when we're serialising potentially anything.

2024-06-16 16:11 UTC, adamrodger commented on src/PactNet/Drivers/HttpInteractionDriver.cs
> +                var jsonValue = System.Text.Json.JsonSerializer.Serialize(value);
style: Don't use var when it's not obvious what the type is 

style: Don't use fully qualified references inline, use an import instead

2024-06-16 16:11 UTC, adamrodger commented on src/PactNet/Drivers/MessageInteractionDriver.cs
> +using System.Text.Json.Serialization;
style: Blank line after import statements

2025-06-20 17:04 UTC, scrocquesel-ml150 commented on src/PactNet.Abstractions/IMessageBuilder.cs
> +        IMessageBuilderV3 Given(string providerState, IDictionary<string, object> parameters);
Could it be a `dynamic` ? It would be aligned with `WithContent`.
Could it be planned for the next major version ?

2025-10-22 21:38 UTC, closed without merging